### PR TITLE
fix(#134): Update YAKS release process

### LINKED ISSUE #134: Update YAKS release process
- Update YAKS release process to align with latest and greatest Camel K release process 
- Prepare OLM catalog resources for PR on OLM repository so YAKS operator is available in the OperatorHub
- Use improved operator installation process
- Fix license headers
- Generate CRDs from Go code
- Update Go client generation
- Use apiGroup domain `yaks.citrusframework.org`
- Use 0.1.0-SNAPSHOT as next version
- Update snapshot release process (use github actions instead of goreleaser)

### PR DESCRIPTION
**Pull request by christophd**
Fixes #134 

Derived from Camel K release process and latest and greatest changes on operator code in Camel K.

- Update YAKS release process to align with latest and greatest Camel K release process
- Prepare OLM catalog resources for PR on OLM repository so YAKS operator is available in the OperatorHub
- Use improved operator installation process
- Fix license headers
- Generate CRDs from Go code
- Update Go client generation
- Use apiGroup domain yaks.citrusframework.org
- Use 0.1.0-SNAPSHOT as next version
- Update snapshot release process (use github actions instead of goreleaser)

### CODE REVIEW

File: pkg/controller/test/test_controller.go [hunk 1]
```diff
@@ -80,7 +97,7 @@ func add(mgr manager.Manager, r reconcile.Reconciler) error {
 			pod := a.Object.(*v1.Pod)
 			var requests []reconcile.Request
 
-			if testName, ok := pod.Labels["org.citrusframework.yaks/test"]; ok {
+			if testName, ok := pod.Labels["yaks.citrusframework.org/test"]; ok {
```
Comment (nicolaferraro) [inline pkg/controller/test/test_controller.go:100]: Right!

File: pkg/install/openshift.go [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+		"The `yaks` binary can be used to both configure the cluster and run tests. " +
+		"Once you've downloaded the `yaks` binary, log into the cluster using the `oc` client tool and start using the `yaks` CLI.\n\n" +
+		"You can run `yaks help` to list the available commands for more information."
+
+	// YaksCLIDownloadURLTemplate is the download template with 3 missing parameters (version, version, os)
+	YaksCLIDownloadURLTemplate = "https://github.com/citrusframework/yaks/releases/download/v%s/yaks-client-%s-%s-64bit.tar.gz"
+)
+
+// OpenShiftConsoleDownloadLink installs the download link for the OpenShift console
+func OpenShiftConsoleDownloadLink(ctx context.Context, c client.Client) error {
```
Comment (nicolaferraro) [inline pkg/install/openshift.go:59]: Great!

File: deploy/operator-role-olm.yaml [hunk 3]
```diff
@@ -0,0 +1,131 @@
+# ---------------------------------------------------------------------------
```
Comment (nicolaferraro) [inline deploy/operator-role-olm.yaml:1]: I think the main reason why we have a double version of roles in Camel K is that you could install camel k in a namespace as a standard user, and the core operator is installed, even if you don't have rights to see some resources (e.g. you don't have access to Knative resources for some reasons).

So e.g. this file usually contain everything and cannot be installed by standard users, so we use it only in OLM where there are no restrictions. And we have other files that contain all the various parts, that the installer tries to install one at time and doesn't fail in case of error.

You can decide to manage things the same way, or just say "you need to be a cluster admin to install yaks", to simplify things.

**Review by nicolaferraro — COMMENTED** [review]
Sounds good, there are some parts that probably are not needed (see comments).

Now that the installation is going to be standardized, I think we should give a single option to install the operator only globally on a cluster. 
So you install it once and then you just run the tests in each namespace. This way you don't have to care about permissions, you don't have to make sure it's installed before running a test... also users just see tests running, and not seeing the operator makes people more happy.

File: deploy/operator-role-olm.yaml (hunk 3 above)
Comment (christophd) [reply deploy/operator-role-olm.yaml:1]: Yep I also noticed that openshift and kubernetes roles in YAKS are identical at the moment. So et the end everything could be consolidated to one single operator-role configuration. But I think I leave it as it is now so we are set for possible future development where YAKS roles for openshift and kubernetes start diverging.
